[profile.default]
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
optimizer = true
optimize_runs = 1000000

[profile.default.optimizer_details]
yul = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
imx-testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://rpc.testnet.immutable.com", chain = 13473 }